service: ce6-12sept-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
